# Generated by Django 3.0.5 on 2020-12-21 13:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20201213_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='userid',
            field=models.CharField(default='', max_length=9),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=20, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=20, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
