# Generated by Django 3.0.5 on 2020-12-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20201221_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='message',
            field=models.CharField(default='', max_length=50),
        ),
    ]
