# Generated by Django 3.0.5 on 2020-12-31 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20201226_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ranking',
            field=models.BooleanField(default=True),
        ),
    ]
