# Generated by Django 3.0.5 on 2020-12-31 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_user_ranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='message',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
