# Generated by Django 3.0.5 on 2020-12-24 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0003_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='receiver',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='request',
            name='sender',
            field=models.IntegerField(),
        ),
    ]
