# Generated by Django 3.0.5 on 2020-12-09 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_record', '0004_auto_20201209_0119'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
