# Generated by Django 3.0.5 on 2020-12-13 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_record', '0005_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='color',
        ),
    ]
