# Generated by Django 3.0.5 on 2020-12-13 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_record', '0006_remove_record_color'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
