# Generated by Django 3.0.5 on 2021-01-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_record', '0007_delete_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('date', models.DateField()),
                ('minutes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('date', models.DateField()),
                ('minutes', models.IntegerField(default=0)),
            ],
        ),
    ]
