# Generated by Django 3.0.5 on 2021-01-02 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anki', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabulary',
            name='user',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
