# Generated by Django 3.0.5 on 2021-01-02 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anki', '0002_auto_20210103_0036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vocabulary',
            old_name='stage',
            new_name='state',
        ),
    ]
