# Generated by Django 3.0.5 on 2021-01-03 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anki', '0003_auto_20210103_0039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vocabulary',
            old_name='meaning',
            new_name='foreign',
        ),
        migrations.RenameField(
            model_name='vocabulary',
            old_name='vocab',
            new_name='japanese',
        ),
    ]
